/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAL.DatabaseManager;
import java.time.LocalDate;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author vukos
 */
public class IntakeForm extends javax.swing.JFrame {
        DatabaseManager dbManager = new DatabaseManager();

    /**
     * Creates new form IntakeForm
     */
    public IntakeForm() {
        initComponents();
    }
    
    public void clearFields() {
        nameTextField.setText("");
        breedTextField.setText("");
        intakedatePicker.setDate(null);
        typebuttonGroup.clearSelection();
        adoptionFeeTextField.setText("0.00");
        yearsSpinner.setValue(0);
        monthsSpinner.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typebuttonGroup = new javax.swing.ButtonGroup();
        headerPanel = new javax.swing.JPanel();
        intakeLabel = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        breedLabel = new javax.swing.JLabel();
        intakeDateLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        childFriendlyLabel = new javax.swing.JLabel();
        energyLabel = new javax.swing.JLabel();
        indoorLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        breedTextField = new javax.swing.JTextField();
        intakedatePicker = new com.github.lgooddatepicker.components.DatePicker();
        dogRadioButton = new javax.swing.JRadioButton();
        catRadioButton = new javax.swing.JRadioButton();
        energyComboBox = new javax.swing.JComboBox<>();
        indoorComboBox = new javax.swing.JComboBox<>();
        childFriendlyComboBox = new javax.swing.JComboBox<>();
        helpButton = new javax.swing.JButton();
        AdoptionFeeLabel = new javax.swing.JLabel();
        adoptionFeeTextField = new javax.swing.JTextField();
        yearsSpinner = new javax.swing.JSpinner();
        yearsLabel = new javax.swing.JLabel();
        monthsLabel = new javax.swing.JLabel();
        monthsSpinner = new javax.swing.JSpinner();
        footerPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(0, 0, 153));

        intakeLabel.setText("Intake Portal");
        intakeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        intakeLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(intakeLabel)
                .addGap(258, 258, 258))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(intakeLabel)
                .addGap(20, 20, 20))
        );

        detailPanel.setBackground(new java.awt.Color(204, 204, 204));

        nameLabel.setText("Name");

        ageLabel.setText("Age");

        breedLabel.setText("Breed");

        intakeDateLabel.setText("Intake Date");

        typeLabel.setText("Animal Type");

        childFriendlyLabel.setText("Child Friendly?");

        energyLabel.setText("Energy Level");

        indoorLabel.setText("Is Indoor");

        typebuttonGroup.add(dogRadioButton);
        dogRadioButton.setText("Dog");
        dogRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogRadioButtonActionPerformed(evt);
            }
        });

        typebuttonGroup.add(catRadioButton);
        catRadioButton.setText("Cat");
        catRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadioButtonActionPerformed(evt);
            }
        });

        energyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Medium", "Low", " " }));

        indoorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " " }));

        childFriendlyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " " }));

        helpButton.setText("Help?");
        helpButton.setBackground(new java.awt.Color(0, 102, 153));
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        AdoptionFeeLabel.setText("Adoption Fee");

        adoptionFeeTextField.setText("0.00");

        yearsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        yearsLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        yearsLabel.setText("Years");

        monthsLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        monthsLabel.setText("Months");

        monthsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 11, 1));

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addComponent(AdoptionFeeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addComponent(childFriendlyLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(intakeDateLabel)
                            .addComponent(breedLabel)
                            .addComponent(ageLabel)
                            .addComponent(nameLabel)
                            .addComponent(energyLabel))
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(childFriendlyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(energyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adoptionFeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(indoorLabel)
                                .addGap(43, 43, 43)
                                .addComponent(indoorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detailPanelLayout.createSequentialGroup()
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dogRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(intakedatePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(breedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                                                .addGap(0, 120, Short.MAX_VALUE)
                                                .addComponent(helpButton))
                                            .addGroup(detailPanelLayout.createSequentialGroup()
                                                .addComponent(catRadioButton)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(detailPanelLayout.createSequentialGroup()
                                        .addComponent(yearsLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(yearsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(monthsLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(monthsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(127, Short.MAX_VALUE))))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(yearsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsLabel)
                    .addComponent(monthsLabel)
                    .addComponent(monthsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breedLabel)
                    .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(breedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(helpButton)))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intakeDateLabel)
                    .addComponent(intakedatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLabel)
                    .addComponent(dogRadioButton)
                    .addComponent(catRadioButton))
                .addGap(15, 15, 15)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(energyLabel)
                    .addComponent(energyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(indoorLabel)
                        .addComponent(indoorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(childFriendlyLabel)
                    .addComponent(childFriendlyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdoptionFeeLabel)
                    .addComponent(adoptionFeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        footerPanel.setBackground(new java.awt.Color(153, 153, 153));

        registerButton.setText("Register Pet");
        registerButton.setBackground(new java.awt.Color(0, 102, 153));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back to Dashboard");
        backButton.setAutoscrolls(true);
        backButton.setBackground(new java.awt.Color(0, 102, 153));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(86, 86, 86))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(backButton))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the main screen
        MainDashboard pi = new MainDashboard();
        pi.setVisible(true);
        pi.setVisible(true);
        pi.pack();
        pi.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        String errorMsg = errorHandling();
    
    if (errorMsg.isEmpty()) {
        int years = (int) yearsSpinner.getValue();
        int months = (int) monthsSpinner.getValue();
        int totalMonths = (years * 12) + months;
    
        String petName = nameTextField.getText().trim();
        String breed = breedTextField.getText().trim();
        LocalDate intakeDate = intakedatePicker.getDate();
        
        String animalType = dogRadioButton.isSelected() ? "Dog" : "Cat";
        
        String energy = (String) energyComboBox.getSelectedItem();
        if (energy != null) {
            energy = energy.trim();
        }
        
        Boolean isChildFriendly = "Yes".equals(childFriendlyComboBox.getSelectedItem());
        Boolean isIndoor = "Yes".equals(indoorComboBox.getSelectedItem());
        
        double fee = Double.parseDouble(adoptionFeeTextField.getText());

        String petID = dbManager.generateNextPetID();
        
        boolean success = dbManager.insertPet(petID, petName, totalMonths, breed,intakeDate, animalType, energy,isIndoor, isChildFriendly, fee);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Successfully registered " + petName + "!");
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save pet to database.","Database Error", JOptionPane.ERROR_MESSAGE);
        }
        
    } else {
        JOptionPane.showMessageDialog(this, errorMsg, "Input Errors", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void dogRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogRadioButtonActionPerformed
        // TODO add your handling code here:
        energyComboBox.setEnabled(true); //Dogs have different energy levels
        indoorComboBox.setEnabled(false); //This is Cat specific
        energyComboBox.setSelectedItem("No"); //Default to No for dogs
    }//GEN-LAST:event_dogRadioButtonActionPerformed

    private void catRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catRadioButtonActionPerformed
        // TODO add your handling code here:
        energyComboBox.setEnabled(false); //Hide for cats
        indoorComboBox.setEnabled(true); //Enable for cats
        
    }//GEN-LAST:event_catRadioButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        String message = """
                       Registering a New Pet
                       - Age Entry: Use the Years and Months spinners to accurately record the pet's age. This helps the matching algorithm identify puppies and kittens.
                       - Animal Type: Select 'Dog' or 'Cat' to enable species-specific fields.
                       - Smart Fields: 'Energy Level' is required for dogs, while 'Indoor Status' is required for cats. Irrelevant fields will be disabled automatically.
                       - Adoption Fee: Set the fee required to cover the animal's medical and boarding costs.
                       - Validation: The 'Intake Date' cannot be in the future. All text fields must be filled before registration.
                         """;

        JOptionPane.showMessageDialog(null, message);
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntakeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdoptionFeeLabel;
    private javax.swing.JTextField adoptionFeeTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel breedLabel;
    private javax.swing.JTextField breedTextField;
    private javax.swing.JRadioButton catRadioButton;
    private javax.swing.JComboBox<String> childFriendlyComboBox;
    private javax.swing.JLabel childFriendlyLabel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JRadioButton dogRadioButton;
    private javax.swing.JComboBox<String> energyComboBox;
    private javax.swing.JLabel energyLabel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JComboBox<String> indoorComboBox;
    private javax.swing.JLabel indoorLabel;
    private javax.swing.JLabel intakeDateLabel;
    private javax.swing.JLabel intakeLabel;
    private com.github.lgooddatepicker.components.DatePicker intakedatePicker;
    private javax.swing.JLabel monthsLabel;
    private javax.swing.JSpinner monthsSpinner;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.ButtonGroup typebuttonGroup;
    private javax.swing.JLabel yearsLabel;
    private javax.swing.JSpinner yearsSpinner;
    // End of variables declaration//GEN-END:variables

    public String errorHandling() {
    String error = "";
    
    // Pet Name
    String petName = nameTextField.getText().trim();
    if (petName.isEmpty()) {
        error += "- Name cannot be empty.\n";
    } else if (!petName.matches("[a-zA-Z\\s]+")) {
        error += "- Name should only contain letters and spaces.\n";
    } else if (petName.length() > 30) {
        error += "- Name cannot be longer than 30 characters.\n";
    }
    
    // Breed
    String breed = breedTextField.getText().trim();
    if (breed.isEmpty()) {
        error += "- Breed cannot be empty.\n";
    } else if (!breed.matches("[a-zA-Z\\s]+")) {
        error += "- Breed should only contain letters and spaces.\n";
    } else if (breed.length() > 50) {
        error += "- Breed cannot be longer than 50 characters.\n";
    }
    
    // Intake Date
    LocalDate intakeDate = intakedatePicker.getDate();
    if (intakeDate == null) {
        error += "- Intake date cannot be empty.\n";
    } else {
        LocalDate today = LocalDate.now();
        if (intakeDate.isAfter(today)) {
            error += "- Intake date cannot be in the future.\n";
        }
    }
    
    // Animal Type
    if (!dogRadioButton.isSelected() && !catRadioButton.isSelected()) {
        error += "- Please select an Animal Type (Dog or Cat).\n";
    }
    
    // Age
    int years = (int) yearsSpinner.getValue();
    int months = (int) monthsSpinner.getValue();
    int totalMonths = (years * 12) + months;
    if (totalMonths == 0) {
        error += "- Age cannot be 0 years and 0 months.\n";
    }
    
    // Energy Level (only required for Dogs)
    if (dogRadioButton.isSelected()) {
        String energy = (String) energyComboBox.getSelectedItem();
        if (energy == null || energy.trim().isEmpty() || energy.trim().equals(" ")) {
            error += "- Please select an Energy Level (High/Medium/Low).\n";
        }
    }
    
    // Adoption Fee
    try {
        double fee = Double.parseDouble(adoptionFeeTextField.getText());
        if (fee < 0) {
            error += "- Adoption fee cannot be negative.\n";
        }
    } catch (NumberFormatException e) {
        error += "- Please enter a valid number for the adoption fee (e.g. 875.50).\n";
    }
    
    return error;
}
}
