/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

 
import DAL.DatabaseManager;
import Entity.Pet;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vukos
 */
public class MainDashboard extends javax.swing.JFrame {
    DatabaseManager dbManager = new DatabaseManager();
    private ArrayList<Pet> allPets; 
    /**
     * Creates new form ArchiveHistory
     */
    public MainDashboard() {
        initComponents();
        petTable.setDefaultRenderer(Object.class, new LongStayRowRenderer());
        loadDashboard();
    }
    /**
     * Pulls the current (non-adopted) pets from the database and displays
     * them, then updates the long-stay alert label.
     */
    private void loadDashboard() {
        allPets = dbManager.getAllPets();
        populateTable(allPets);
        updateLongStayLabel(allPets);
    }//loadDashboard
    
     // Fills petTable with the given list of pets.
    private void populateTable(ArrayList<Pet> petsToShow) {
        DefaultTableModel model = (DefaultTableModel) petTable.getModel();
        model.setRowCount(0);
        for (Pet p : petsToShow) {
            model.addRow(new Object[]{
                p.getPetName(),
                p.getType(),
                p.getAgeMonths(),
                p.getAdoptionFee(),
                p.calculateDateInShelter()
            });
        }
    }//populateTable
 
    // Updates the "Long Stay Alert" label with how many current pets have been in the shelter for more than 30 days
    private void updateLongStayLabel(ArrayList<Pet> petsToCheck) {
        long longStayCount = petsToCheck.stream().filter(p -> p.calculateDateInShelter() > 30).count();
        longStayLabel.setText("Long Stay Alert: " + longStayCount
                + " animal(s) over 30 days in shelter");
    }//updateLongStayLabel
 
    // Highlights rows where "Days In Shelter" exceeds 30 days
    private class LongStayRowRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
 
            Object daysValue = table.getModel().getValueAt(row, 4);
            boolean isLongStay = (daysValue instanceof Integer) && ((Integer) daysValue) > 30;
 
            if (!isSelected) {
                c.setBackground(isLongStay ? new Color(255, 205, 205) : Color.WHITE);
            }
            return c;
        }
    }//LongStayRowRenderer

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailPanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        catsButton = new javax.swing.JButton();
        dogsButton = new javax.swing.JButton();
        longStayLabel = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        shelterLabel = new javax.swing.JLabel();
        currentLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        intakeButton = new javax.swing.JButton();
        matchMakerButton = new javax.swing.JButton();
        archiveButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        detailPanel.setBackground(new java.awt.Color(153, 153, 153));

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Animal Type", "Age in Months", "Price", "Days In Shelter"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        petTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tableScrollPane.setViewportView(petTable);

        catsButton.setBackground(new java.awt.Color(0, 102, 153));
        catsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catsButton.setText("Cats Only");
        catsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catsButtonActionPerformed(evt);
            }
        });

        dogsButton.setBackground(new java.awt.Color(0, 102, 153));
        dogsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dogsButton.setText("Dogs Only");
        dogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogsButtonActionPerformed(evt);
            }
        });

        longStayLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        longStayLabel.setText("Long Stay Alert: More than 30 days in shelter");

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addComponent(catsButton)
                                .addGap(33, 33, 33)
                                .addComponent(dogsButton)
                                .addGap(113, 113, 113))
                            .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                        .addComponent(longStayLabel)
                        .addGap(95, 95, 95))))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catsButton)
                    .addComponent(dogsButton))
                .addGap(18, 18, 18)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(longStayLabel)
                .addContainerGap())
        );

        headerPanel.setBackground(new java.awt.Color(0, 0, 153));

        shelterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        shelterLabel.setText("Current Animals");

        currentLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        currentLabel.setText("Shelter Dashboard");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(currentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shelterLabel)
                .addGap(137, 137, 137))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelterLabel)
                    .addComponent(currentLabel))
                .addGap(17, 17, 17))
        );

        buttonPanel.setBackground(new java.awt.Color(204, 204, 204));

        intakeButton.setBackground(new java.awt.Color(0, 102, 153));
        intakeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        intakeButton.setText("Intake Portal");
        intakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intakeButtonActionPerformed(evt);
            }
        });

        matchMakerButton.setBackground(new java.awt.Color(0, 102, 153));
        matchMakerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        matchMakerButton.setText("Match Maker");
        matchMakerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchMakerButtonActionPerformed(evt);
            }
        });

        archiveButton.setBackground(new java.awt.Color(0, 102, 153));
        archiveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        archiveButton.setText("Archive History");
        archiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(0, 102, 153));
        helpButton.setText("Help?");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matchMakerButton)
                    .addComponent(intakeButton))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addComponent(archiveButton)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addComponent(helpButton)
                        .addGap(62, 62, 62))))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(intakeButton)
                .addGap(46, 46, 46)
                .addComponent(matchMakerButton)
                .addGap(49, 49, 49)
                .addComponent(archiveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpButton)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean catsFilterActive = false;
    private boolean dogsFilterActive = false;
    
    private void catsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catsButtonActionPerformed
        // TODO add your handling code here:
        //Only shows the available pets that are cats
        catsFilterActive = !catsFilterActive;
        dogsFilterActive = false;
 
        if (catsFilterActive) {
            ArrayList<Pet> catsOnly = new ArrayList<>();
            for (Pet p : allPets) {
                if ("Cat".equalsIgnoreCase(p.getType())) {
                    catsOnly.add(p);
                }
            }
            populateTable(catsOnly);
            updateLongStayLabel(catsOnly);
        } else {
            populateTable(allPets);
            updateLongStayLabel(allPets);
        }
    }//GEN-LAST:event_catsButtonActionPerformed

    private void intakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the intake screen
        IntakeForm pi = new IntakeForm();
        pi.setVisible(true);
        pi.setVisible(true);
        pi.pack();
        pi.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_intakeButtonActionPerformed

    private void matchMakerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchMakerButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the match maker screen
        MatchMakerHub pi = new MatchMakerHub();
        pi.setVisible(true);
        pi.setVisible(true);
        pi.pack();
        pi.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_matchMakerButtonActionPerformed

    private void archiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the archive history screen
        ArchiveHistory pi = new ArchiveHistory();
        pi.setVisible(true);
        pi.setVisible(true);
        pi.pack();
        pi.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_archiveButtonActionPerformed

    private void dogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogsButtonActionPerformed
        // TODO add your handling code here:
        //Only shows the available pets that are dogs
        dogsFilterActive = !dogsFilterActive;
        catsFilterActive = false;
 
        if (dogsFilterActive) {
            ArrayList<Pet> dogsOnly = new ArrayList<>();
            for (Pet p : allPets) {
                if ("Dog".equalsIgnoreCase(p.getType())) {
                    dogsOnly.add(p);
                }
            }
            populateTable(dogsOnly);
            updateLongStayLabel(dogsOnly);
        } else {
            populateTable(allPets);
            updateLongStayLabel(allPets);
        }
    }//GEN-LAST:event_dogsButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        String message = """
                         Dashboard Navigation & Overview
                         - View Pets: The table shows all animals currently in the shelter.
                         - Filtering: Use the 'Cats Only' or 'Dogs Only' buttons to quickly sort the list by species.
                         - Long Stay Alert: Animals that have been in the shelter for more than 30 days are automatically flagged. Look for the "Days in Shelter" column to prioritize these animals for adoption.
                         - Navigation: Use the sidebar buttons to add new pets (Intake), find matches (Match Maker), or view past success stories (History).
                       
                         """;

        JOptionPane.showMessageDialog(null, message);
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archiveButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton catsButton;
    private javax.swing.JLabel currentLabel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JButton dogsButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton intakeButton;
    private javax.swing.JLabel longStayLabel;
    private javax.swing.JButton matchMakerButton;
    private javax.swing.JTable petTable;
    private javax.swing.JLabel shelterLabel;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
