/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAL.DatabaseManager;
import Entity.Adopter;
import Entity.Pet;
import Utility.CompatabiltyCalculator;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vukosi
 */
public class MatchMakerHub extends javax.swing.JFrame {

    DatabaseManager dbManager = new DatabaseManager();
    private ArrayList<Pet> matchedPets = new ArrayList<>();
    /**
     * Creates new form MatchMakerHub
     */
    public MatchMakerHub() {
        initComponents();
        
        //Hides the first column of the table
        if (matchesTable.getColumnCount() > 0) {
            matchesTable.getColumnModel().getColumn(0).setMinWidth(0);
            matchesTable.getColumnModel().getColumn(0).setMaxWidth(0);
            matchesTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        }
    }

    public void clearFields(){
        fullNameTextField.setText("");
        idTextField.setText("");
        addressTextField.setText("");
        numberTextField.setText("");
        kidsbuttonGroup.clearSelection();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kidsbuttonGroup = new javax.swing.ButtonGroup();
        detailPanel = new javax.swing.JPanel();
        matchesScrollPane = new javax.swing.JScrollPane();
        matchesTable = new javax.swing.JTable();
        adopterLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        kidsLabel = new javax.swing.JLabel();
        activityLabel = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        homeComboBox = new javax.swing.JComboBox<>();
        findButton = new javax.swing.JButton();
        markButton = new javax.swing.JButton();
        fullNameTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        helpButton = new javax.swing.JButton();
        numberLabel = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        animalComboBox = new javax.swing.JComboBox<>();
        animalLabel = new javax.swing.JLabel();
        activityComboBox = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        matchMakerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        detailPanel.setBackground(new java.awt.Color(153, 153, 153));

        matchesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Matching Pets", "Animal Type", "Compatability Score", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        matchesScrollPane.setViewportView(matchesTable);

        adopterLabel.setText("Adopter Inputs:");

        fullNameLabel.setText("Full Name");

        idLabel.setText("Identity Number");

        addressLabel.setText("Residential Address");

        homeLabel.setText("Home Type");

        kidsLabel.setText("Do you have Kids?");

        activityLabel.setText("Preffered Activity Level");

        kidsbuttonGroup.add(yesRadioButton);
        yesRadioButton.setText("Yes");

        kidsbuttonGroup.add(noRadioButton);
        noRadioButton.setText("No");

        homeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartment", "House with small yard", "House with large yard" }));

        findButton.setBackground(new java.awt.Color(0, 102, 153));
        findButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        findButton.setText("Find Matches");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        markButton.setBackground(new java.awt.Color(0, 102, 153));
        markButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        markButton.setText("Mark As Adopted");
        markButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markButtonActionPerformed(evt);
            }
        });

        addressTextField.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        addressTextField.setText("Street,Postal Code");

        helpButton.setBackground(new java.awt.Color(0, 102, 153));
        helpButton.setText("Help?");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        numberLabel.setText("Phone Number");

        animalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat", "Either", " ", " " }));

        animalLabel.setText("Animal Type");

        activityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High", " " }));

        backButton.setBackground(new java.awt.Color(0, 102, 153));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabel)
                                    .addComponent(fullNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailPanelLayout.createSequentialGroup()
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kidsLabel)
                                            .addComponent(homeLabel))
                                        .addGap(33, 33, 33)
                                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(homeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(detailPanelLayout.createSequentialGroup()
                                                .addComponent(yesRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(noRadioButton))))
                                    .addComponent(animalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailPanelLayout.createSequentialGroup()
                                        .addComponent(activityLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(activityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(adopterLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(detailPanelLayout.createSequentialGroup()
                                    .addComponent(addressLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(detailPanelLayout.createSequentialGroup()
                                .addComponent(numberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(animalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                        .addComponent(findButton)
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                        .addComponent(markButton)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                        .addComponent(matchesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(helpButton)
                            .addComponent(backButton))
                        .addGap(25, 25, 25))))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(adopterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameLabel)
                    .addComponent(homeLabel)
                    .addComponent(homeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kidsLabel)
                        .addComponent(yesRadioButton)
                        .addComponent(noRadioButton)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel)
                    .addComponent(activityLabel)
                    .addComponent(activityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberLabel)
                    .addComponent(animalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animalLabel))
                .addGap(28, 28, 28)
                .addComponent(findButton)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(helpButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matchesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(markButton)
                .addGap(18, 18, 18))
        );

        headerPanel.setBackground(new java.awt.Color(0, 0, 153));

        matchMakerLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        matchMakerLabel.setText("Match Maker Hub");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(matchMakerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(matchMakerLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void markButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markButtonActionPerformed
        // TODO add your handling code here:
    // Check which row is highlighted in the JTable
    int selectedRow = matchesTable.getSelectedRow();

    // Ensure a pet was actually selected
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a pet from the list first!", "No Selection", JOptionPane.WARNING_MESSAGE);
        return; 
    }
        if (errorHandling().equals("")) {
            //Collect data
            String fullName = fullNameTextField.getText().trim();
            String idNumber = idTextField.getText().trim();
            String address = addressTextField.getText().trim();
            int contactNumber = Integer.parseInt(numberTextField.getText());
            String homeType = homeComboBox.getSelectedItem().toString();
            Boolean hasKids = yesRadioButton.isSelected();
            String type = animalComboBox.getSelectedItem().toString();
            String activityPreference = (String) activityComboBox.getSelectedItem();

            String hiddenPetID = matchesTable.getValueAt(selectedRow, 0).toString();
            Double adoptionFee = Double.valueOf(matchesTable.getValueAt(selectedRow, 4).toString());
            
            String adopterID = dbManager.generateNextAdopterID();
            
            
            boolean adopterSaved = dbManager.insertAdopter(adopterID,fullName,idNumber,address,contactNumber,homeType,hasKids,activityPreference);
            //Only if the adopter is saved will the adoption be proccessed
            if (adopterSaved) {
                dbManager.processAdoption(hiddenPetID,adopterID,adoptionFee); 
                JOptionPane.showMessageDialog(rootPane, "Adopter was submitted successfully." );
                clearFields(); //Clear the input fields

                //Takes you to the main screen
                MainDashboard pi = new MainDashboard();
                pi.setVisible(true);
                pi.setVisible(true);
                pi.pack();
                pi.setLocationRelativeTo(null);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save Adopter, Adoption cancelled", "Database Error", JOptionPane.ERROR_MESSAGE);
            }
    
        } else {
                JOptionPane.showMessageDialog(rootPane, "Database Error: Could not save pet.", "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(rootPane, errorHandling());
        }//else
        
        //Takes you to the main screen
        MainDashboard pi = new MainDashboard();
        pi.setVisible(true);
        pi.setVisible(true);
        pi.pack();
        pi.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_markButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        // TODO add your handling code here:
         String error = errorHandling();
        if (!error.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, error, "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Build a temporary Adopter object from the form inputs so the calculator has something to compare every pet against.
        Adopter adopter = new Adopter(
                null,
                fullNameTextField.getText().trim(),
                idTextField.getText().trim(),
                addressTextField.getText().trim(),
                Integer.parseInt(numberTextField.getText().trim()),
                homeComboBox.getSelectedItem().toString(),
                yesRadioButton.isSelected(),
                (String) activityComboBox.getSelectedItem()
        );
 
        String desiredType = animalComboBox.getSelectedItem().toString().trim();
 
        matchedPets = new ArrayList<>();
        for (Pet p : dbManager.getAllPets()) {
            // Keeps in mind the "Dog"/"Cat" filter, "Either" (or blank) considers all pets
            if (!desiredType.equalsIgnoreCase("Either") && !desiredType.isBlank()
                    && !p.getType().equalsIgnoreCase(desiredType)) {
                continue;
            }
            double score = CompatabiltyCalculator.calculateScore(adopter, p);
            p.setScore(score);
            matchedPets.add(p);
        }//for
 
        // Highest compatibility first
        matchedPets.sort(Comparator.comparingDouble(Pet::getScore).reversed());
 
        DefaultTableModel model = (DefaultTableModel) matchesTable.getModel();
        model.setRowCount(0); // Clear old results
 
        for (Pet p : matchedPets) {
            // Add the ID at the start, followed by what the user sees
            model.addRow(new Object[]{
                p.getPetID(),       // Column 0 (HIDDEN)
                p.getPetName(),     // Column 1 (Matching Pets)
                p.getType(),     // Column 2 (Animal Type)
                p.getScore() + "%", // Column 3 (Compatibility)
                p.getAdoptionFee()        // Column 4 (Price)
            });
        }//for
 
        if (matchedPets.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No pets matched the selected animal type.");
        }
 
        applyFormatting();
    }//GEN-LAST:event_findButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        String message = """
                      Using the Lifestyle Matching Algorithm
                      - Step 1: Enter the potential adopter's details (Name, ID, Contact).
                      - Step 2: Select the adopter's lifestyle criteria (Home type, Kids, Activity level).
                      - Step 3: Click 'Find Matches' to run the algorithm. Pets are scored out of 100% based on how well their traits (Size, Energy, Child-friendliness) fit the adopter's home.
                      - Step 4: Select a pet from the results and click 'Mark as Adopted' to finalize the process. This will move the record to the Archive and update the database. 
                         """;

        JOptionPane.showMessageDialog(null, message);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        //Takes you to the main screen
        MainDashboard pi = new MainDashboard();
        pi.setVisible(true);
        pi.setVisible(true);
        pi.pack();
        pi.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchMakerHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchMakerHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchMakerHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchMakerHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatchMakerHub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activityComboBox;
    private javax.swing.JLabel activityLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel adopterLabel;
    private javax.swing.JComboBox<String> animalComboBox;
    private javax.swing.JLabel animalLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JComboBox<String> homeComboBox;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel kidsLabel;
    private javax.swing.ButtonGroup kidsbuttonGroup;
    private javax.swing.JButton markButton;
    private javax.swing.JLabel matchMakerLabel;
    private javax.swing.JScrollPane matchesScrollPane;
    private javax.swing.JTable matchesTable;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables

    public String errorHandling() {
        String error = "";
        //For ID number
        String id = idTextField.getText().trim();
        
        if (id.isEmpty() || id.isBlank()) {
            error += "-ID cannot be empty.\n";
        } else if (id.length() != 13) {
            error += "-ID must be 13 digits\n"; 
        } else {
            try {
                long idAsNumber = Long.parseLong(id);
            // If it reaches this line, it is a valid number
            } catch (NumberFormatException e) {
            // If the user typed letters, the code "jumps" here
                error += "-ID can only contain digits.\n";
            }
        }//else 
        
        //For FullName
        String fullName = fullNameTextField.getText();
        if (fullName.isEmpty() || fullName.isBlank()) {
            error += "-Full name cannot be blank.\n";
        }
        else if (!fullName.matches("^[a-zA-Z ]*$")) {
            //Ensures only letters are entered, and allows spaces as the FULL name is requested
            error += "-Full name can only contain letters\n";
        }
        else if (fullName.length() > 25) {
            error += "Full name can not exceed 25 characters\n";
        }
        
        //For contact number
        String number = numberTextField.getText().trim();
        
        if (number.isEmpty() || number.isBlank()) {
            error += "-Contact Number cannot be empty.\n";
        } else if (number.length() != 10) {
            error += "-Contact Number must be 10 digits\n"; 
        } else {
            try {
                long ContactNumber = Long.parseLong(number);
            // If it reaches this line, it is a valid number
            } catch (NumberFormatException e) {
            // If the user typed letters, the code "jumps" here
                error += "-Contact can only contain digits.\n";
            }
        }//else
        
        //For Address 
        String address = addressTextField.getText();

        if (!address.isEmpty()) {
            String[] split = address.split(",");
            if (split.length != 2) {
                error+= "-Address must be in the format Street, Postal Code\n";
            } else {
                String street = split[0].trim();
                String postalCode = split[1].trim();
                if (postalCode.length() != 4 || !postalCode.matches("^[0-9]*$")) {
                    error+= "-Postal code must be 4 digits\n";
                }
            }
        } else {
            error += "-Address cannot be empty.\n";
        }
            
        return error;
    }//Errorhandling
    
    public void applyFormatting() {
        matchesTable.getColumnModel().getColumn(0).setMinWidth(0);
        matchesTable.getColumnModel().getColumn(0).setMaxWidth(0);
        matchesTable.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
}
